class Tables {
  static BULK_READ = {
    TABLE: "BulkRead",
    ROWID: "ROWID",
    CRMJOBID: "CRMJOBID",
    REQUESTED_PAGE_NO: "REQUESTED_PAGE_NO",
    FETCHED_PAGE_NO: "FETCHED_PAGE_NO",
    MODULE_NAME: "MODULE_NAME",
    DOWNLOAD_URL: "DOWNLOAD_URL",
    FIELDS_TO_BE_PROCESSED: "FIELDS_TO_BE_PROCESSED"
  };

  static READ_QUEUE = {
    TABLE: "ReadQueue",
    ROWID: "ROWID",
    CRM_JOB_ID: "CRM_JOB_ID",
    FILEID: "FILEID",
    LINE_PROCESSED: "LINE_PROCESSED",
    IS_PROCESS_STARTED: "IS_PROCESS_STARTED",
    IS_PROCESS_COMPLETED: "IS_PROCESS_COMPLETED",
    MODULE: "MODULE"
  };

  static WRITE_QUEUE = {
    TABLE: "WriteQueue",
    ROWID: "ROWID",
    CRM_JOB_ID: "CRM_JOB_ID",
    FILE_ID: "FILE_ID",
    IS_UPLOADED: "IS_UPLOADED",
    MODULE: "MODULE"
  };
}
module.exports = Tables;
